version: 1
disable_existing_loggers: false

formatters:
  console:
    class: ss_utils_logging.formatters.ConsoleFormatter
    format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    class: ss_utils_logging.formatters.ORJSONFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
    level: DEBUG

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: logs/app.json
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: INFO

loggers:
  # Application loggers
  main:
    level: INFO

  # Gunicorn/Uvicorn loggers
  gunicorn.access:
    level: INFO
    handlers: [console]
    propagate: true

  gunicorn.error:
    level: INFO
    handlers: [console]
    propagate: true

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: true

  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: true

  # ML/AI libraries
  optimum:
    level: WARNING

  torch:
    level: WARNING

  transformers:
    level: WARNING

  # Async/WebSocket libraries
  asyncio:
    level: WARNING

  websockets:
    level: WARNING


  # Other libraries
  concurrent.futures:
    level: WARNING

  # HTTP libraries
  httpx:
    level: WARNING

  httpcore:
    level: WARNING

  urllib3.connectionpool:
    level: WARNING

root:
  level: INFO
  handlers: [console, file]