version: 1
disable_existing_loggers: false

formatters:
  console:
    class: ss_utils_logging.formatters.ConsoleFormatter
    format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    class: ss_utils_logging.formatters.ORJSONFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
    level: DEBUG

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: logs/app.json
    maxBytes: 10485760  # 10MB
    backupCount: 5
    level: INFO

loggers:
  # Suppress noisy external libraries
  uvicorn.access:
    level: WARNING
    propagate: false

  uvicorn.error:
    level: INFO
    propagate: true

  httpx:
    level: WARNING
    propagate: true

  httpcore:
    level: WARNING
    propagate: true

  urllib3.connectionpool:
    level: WARNING
    propagate: true

root:
  level: INFO
  handlers: [console, file]